# Generated by Django 4.1.7 on 2023-05-02 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autenticacao', '0004_endereco_bairro_endereco_cidade_endereco_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
