# Generated by Django 4.1.7 on 2023-05-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0010_alter_dadosusuario_cpf_alter_dadosusuario_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
