# Generated by Django 4.1.7 on 2023-05-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0011_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosusuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
