# Generated by Django 4.1.7 on 2023-05-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0012_alter_dadosusuario_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='padrao',
            field=models.BooleanField(default=False),
        ),
    ]
