# Generated by Django 4.1.7 on 2023-05-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='qtd_total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
