# Generated by Django 4.1.7 on 2023-05-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_categoria_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='lancamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
